name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup gcloud cli
        run: |
          wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
          tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --quiet --usage-reporting=false --path-update=true
          PATH="google-cloud-sdk/bin:${PATH}"
          gcloud --quiet components update

      - name: setup staging dir
        run: |
          mkdir staging
          cp ./main.py ./staging
          cp ./requirements.txt ./staging

      - name: deploy cloud function
        working-directory: ./staging
        run: |
          printf "%s" '${{ secrets.GCF_DEPLOYER_KEY }}' > key-file.json
          gcloud auth activate-service-account --key-file=key-file.json
          rm key-file.json
          gcloud functions deploy pubsub-to-notion-page-builder \
          --runtime python39 \
          --entry-point create_notion_page \
          --region us-central1 \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --no-gen2 \
          --memory 128MB \
          --trigger-topic create-notion-page \
          --set-env-vars TOKEN_V2="${{ secrets.TOKEN_V2 }}"
